
export const RULE_VALUES = {

 RULE_FAIL_POINTS : 0,
 POINTS_FOR_RULE_2 : 50,
 POINTS_FOR_RULE_3 : 25,
 ITEM_GROUP_COUNT_RULE_4 : 2,
 POINTS_FOR_RULE_4 : 5,
 CHAR_MULTIPLES_RULE_5 : 3,
 MULTIPLY_BY_FOR_RULE_5 : 0.2,
 POINTS_PER_ODD_PURCHASE_DATE : 6,
 TIME_LOWER_LIMIT_RULE_7 : 14,
 TIME_UPPER_LIMIT_RULE_7 : 16,
 POINTS_FOR_RULE_7 : 10,
}
